# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biddergy3.ui'
#
# Created: Mon Nov 14 18:44:41 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 784)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imgBiddergyLogo = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgBiddergyLogo.sizePolicy().hasHeightForWidth())
        self.imgBiddergyLogo.setSizePolicy(sizePolicy)
        self.imgBiddergyLogo.setText("")
        self.imgBiddergyLogo.setPixmap(QtGui.QPixmap("img/biddergy_new_logo.png"))
        self.imgBiddergyLogo.setScaledContents(True)
        self.imgBiddergyLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBiddergyLogo.setObjectName("imgBiddergyLogo")
        self.horizontalLayout_2.addWidget(self.imgBiddergyLogo)
        self.txtSearch = QtGui.QLineEdit(self.widget_2)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout_2.addWidget(self.txtSearch)
        self.comSearchType = QtGui.QComboBox(self.widget_2)
        self.comSearchType.setObjectName("comSearchType")
        self.comSearchType.addItem("")
        self.comSearchType.addItem("")
        self.comSearchType.addItem("")
        self.horizontalLayout_2.addWidget(self.comSearchType)
        self.pushButton = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.tab_myAccount = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_myAccount.sizePolicy().hasHeightForWidth())
        self.tab_myAccount.setSizePolicy(sizePolicy)
        self.tab_myAccount.setMinimumSize(QtCore.QSize(460, 410))
        self.tab_myAccount.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_myAccount.setTabsClosable(False)
        self.tab_myAccount.setObjectName("tab_myAccount")
        self.tabSummary = QtGui.QWidget()
        self.tabSummary.setObjectName("tabSummary")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabSummary)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.tabSummary)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnRefreshSummary = QtGui.QPushButton(self.tab_2)
        self.btnRefreshSummary.setGeometry(QtCore.QRect(360, 290, 85, 27))
        self.btnRefreshSummary.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btnRefreshSummary.setObjectName("btnRefreshSummary")
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(0, 10, 87, 134))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblWatching = QtGui.QLabel(self.widget)
        self.lblWatching.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblWatching.setObjectName("lblWatching")
        self.gridLayout.addWidget(self.lblWatching, 0, 0, 1, 1)
        self.lblBidding = QtGui.QLabel(self.widget)
        self.lblBidding.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblBidding.setObjectName("lblBidding")
        self.gridLayout.addWidget(self.lblBidding, 1, 0, 1, 1)
        self.lblWon = QtGui.QLabel(self.widget)
        self.lblWon.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblWon.setObjectName("lblWon")
        self.gridLayout.addWidget(self.lblWon, 2, 0, 1, 1)
        self.lblNotWon = QtGui.QLabel(self.widget)
        self.lblNotWon.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblNotWon.setObjectName("lblNotWon")
        self.gridLayout.addWidget(self.lblNotWon, 3, 0, 1, 1)
        self.lblPurchases = QtGui.QLabel(self.widget)
        self.lblPurchases.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblPurchases.setObjectName("lblPurchases")
        self.gridLayout.addWidget(self.lblPurchases, 4, 0, 1, 1)
        self.lblInvoices = QtGui.QLabel(self.widget)
        self.lblInvoices.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblInvoices.setObjectName("lblInvoices")
        self.gridLayout.addWidget(self.lblInvoices, 5, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.valWatching = QtGui.QLabel(self.widget)
        self.valWatching.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.valWatching.setObjectName("valWatching")
        self.gridLayout_3.addWidget(self.valWatching, 0, 0, 1, 1)
        self.valBidding = QtGui.QLabel(self.widget)
        self.valBidding.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.valBidding.setObjectName("valBidding")
        self.gridLayout_3.addWidget(self.valBidding, 1, 0, 1, 1)
        self.valWon = QtGui.QLabel(self.widget)
        self.valWon.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.valWon.setObjectName("valWon")
        self.gridLayout_3.addWidget(self.valWon, 2, 0, 1, 1)
        self.valNotWon = QtGui.QLabel(self.widget)
        self.valNotWon.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.valNotWon.setObjectName("valNotWon")
        self.gridLayout_3.addWidget(self.valNotWon, 3, 0, 1, 1)
        self.valPurchases = QtGui.QLabel(self.widget)
        self.valPurchases.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.valPurchases.setObjectName("valPurchases")
        self.gridLayout_3.addWidget(self.valPurchases, 4, 0, 1, 1)
        self.valInvoices = QtGui.QLabel(self.widget)
        self.valInvoices.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.valInvoices.setObjectName("valInvoices")
        self.gridLayout_3.addWidget(self.valInvoices, 5, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 1, 1, 2)
        self.tab_myAccount.addTab(self.tabSummary, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.wid_statusBlock = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_statusBlock.sizePolicy().hasHeightForWidth())
        self.wid_statusBlock.setSizePolicy(sizePolicy)
        self.wid_statusBlock.setMinimumSize(QtCore.QSize(270, 160))
        self.wid_statusBlock.setObjectName("wid_statusBlock")
        self.val_itemTitle = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemTitle.setGeometry(QtCore.QRect(10, 5, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.val_itemTitle.setFont(font)
        self.val_itemTitle.setObjectName("val_itemTitle")
        self.val_itemFormat = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemFormat.setGeometry(QtCore.QRect(10, 26, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.val_itemFormat.setFont(font)
        self.val_itemFormat.setObjectName("val_itemFormat")
        self.val_itemCurrentPrice = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemCurrentPrice.setGeometry(QtCore.QRect(180, 50, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.val_itemCurrentPrice.setFont(font)
        self.val_itemCurrentPrice.setFrameShadow(QtGui.QFrame.Plain)
        self.val_itemCurrentPrice.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.val_itemCurrentPrice.setObjectName("val_itemCurrentPrice")
        self.lbl_itemBids = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemBids.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.lbl_itemBids.setObjectName("lbl_itemBids")
        self.lbl_itemLocation = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemLocation.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.lbl_itemLocation.setObjectName("lbl_itemLocation")
        self.lbl_itemStarts = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemStarts.setGeometry(QtCore.QRect(10, 120, 31, 16))
        self.lbl_itemStarts.setObjectName("lbl_itemStarts")
        self.lbl_itemEnds = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemEnds.setGeometry(QtCore.QRect(10, 140, 31, 16))
        self.lbl_itemEnds.setObjectName("lbl_itemEnds")
        self.lbl_itemHighBidder = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemHighBidder.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.lbl_itemHighBidder.setObjectName("lbl_itemHighBidder")
        self.val_itemBids = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemBids.setGeometry(QtCore.QRect(40, 50, 31, 16))
        self.val_itemBids.setObjectName("val_itemBids")
        self.val_itemHighBidder = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemHighBidder.setGeometry(QtCore.QRect(80, 70, 171, 16))
        self.val_itemHighBidder.setObjectName("val_itemHighBidder")
        self.val_itemLocation = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemLocation.setGeometry(QtCore.QRect(60, 100, 191, 16))
        self.val_itemLocation.setObjectName("val_itemLocation")
        self.val_itemStart = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemStart.setGeometry(QtCore.QRect(50, 120, 191, 16))
        self.val_itemStart.setObjectName("val_itemStart")
        self.val_itemEnd = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemEnd.setGeometry(QtCore.QRect(50, 140, 191, 16))
        self.val_itemEnd.setObjectName("val_itemEnd")
        self.lbl_itemLotNumber = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemLotNumber.setGeometry(QtCore.QRect(50, 26, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_itemLotNumber.setFont(font)
        self.lbl_itemLotNumber.setObjectName("lbl_itemLotNumber")
        self.val_itemLotNumber = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemLotNumber.setGeometry(QtCore.QRect(74, 26, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.val_itemLotNumber.setFont(font)
        self.val_itemLotNumber.setObjectName("val_itemLotNumber")
        self.lbl_itemListingNumber = QtGui.QLabel(self.wid_statusBlock)
        self.lbl_itemListingNumber.setGeometry(QtCore.QRect(110, 26, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_itemListingNumber.setFont(font)
        self.lbl_itemListingNumber.setObjectName("lbl_itemListingNumber")
        self.val_itemListingNumber = QtGui.QLabel(self.wid_statusBlock)
        self.val_itemListingNumber.setGeometry(QtCore.QRect(146, 26, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.val_itemListingNumber.setFont(font)
        self.val_itemListingNumber.setObjectName("val_itemListingNumber")
        self.txt_itemDescription = QtGui.QTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txt_itemDescription.sizePolicy().hasHeightForWidth())
        self.txt_itemDescription.setSizePolicy(sizePolicy)
        self.txt_itemDescription.setAutoFillBackground(False)
        self.txt_itemDescription.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txt_itemDescription.setFrameShadow(QtGui.QFrame.Sunken)
        self.txt_itemDescription.setObjectName("txt_itemDescription")
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        self.web_itemImage = QtWebKit.QWebView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.web_itemImage.sizePolicy().hasHeightForWidth())
        self.web_itemImage.setSizePolicy(sizePolicy)
        self.web_itemImage.setUrl(QtCore.QUrl("about:blank"))
        self.web_itemImage.setObjectName("web_itemImage")
        self.gridLayout_6.addWidget(self.web_itemImage, 0, 1, 1, 1)
        self.tab_myAccount.addTab(self.tab, "")
        self.tab_browse = QtGui.QWidget()
        self.tab_browse.setObjectName("tab_browse")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_browse)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_3 = QtGui.QWidget(self.tab_browse)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_8 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listWidget = QtGui.QListWidget(self.widget_3)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_8.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_3, 0, 0, 1, 1)
        self.tab_myAccount.addTab(self.tab_browse, "")
        self.gridLayout_2.addWidget(self.tab_myAccount, 4, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGeneral_Help = QtGui.QAction(MainWindow)
        self.actionGeneral_Help.setObjectName("actionGeneral_Help")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSummary_Refresh = QtGui.QAction(MainWindow)
        self.actionSummary_Refresh.setObjectName("actionSummary_Refresh")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionGeneral_Help)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_myAccount.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(
            QtGui.QApplication.translate("MainWindow", "Biddergy", None, QtGui.QApplication.UnicodeUTF8))
        self.txtSearch.setPlaceholderText(
            QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.comSearchType.setItemText(0, QtGui.QApplication.translate("MainWindow", "Lot #", None,
                                                                       QtGui.QApplication.UnicodeUTF8))
        self.comSearchType.setItemText(1, QtGui.QApplication.translate("MainWindow", "Listing #", None,
                                                                       QtGui.QApplication.UnicodeUTF8))
        self.comSearchType.setItemText(2, QtGui.QApplication.translate("MainWindow", "Keyword", None,
                                                                       QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(
            QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_myAccount.setToolTip(
            QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.tabSummary.setToolTip(
            QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.btnRefreshSummary.setText(
            QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWatching.setText(
            QtGui.QApplication.translate("MainWindow", "Watching:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBidding.setText(
            QtGui.QApplication.translate("MainWindow", "Bidding:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblWon.setText(QtGui.QApplication.translate("MainWindow", "Won:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNotWon.setText(
            QtGui.QApplication.translate("MainWindow", "Not Won:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPurchases.setText(
            QtGui.QApplication.translate("MainWindow", "Purchases:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInvoices.setText(
            QtGui.QApplication.translate("MainWindow", "Invoices:", None, QtGui.QApplication.UnicodeUTF8))
        self.valWatching.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.valBidding.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.valWon.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.valNotWon.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.valPurchases.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.valInvoices.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  QtGui.QApplication.translate("MainWindow", "Summary", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  QtGui.QApplication.translate("MainWindow", "Watching", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4),
                                  QtGui.QApplication.translate("MainWindow", "Bidding", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5),
                                  QtGui.QApplication.translate("MainWindow", "Won", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6),
                                  QtGui.QApplication.translate("MainWindow", "Not Won", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7),
                                  QtGui.QApplication.translate("MainWindow", "Purchases", None,
                                                               QtGui.QApplication.UnicodeUTF8))
        self.tab_myAccount.setTabText(self.tab_myAccount.indexOf(self.tabSummary),
                                      QtGui.QApplication.translate("MainWindow", "My Account", None,
                                                                   QtGui.QApplication.UnicodeUTF8))
        self.val_itemTitle.setText(
            QtGui.QApplication.translate("MainWindow", "Item Title", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemFormat.setText(
            QtGui.QApplication.translate("MainWindow", "format", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemCurrentPrice.setText(
            QtGui.QApplication.translate("MainWindow", "$0", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemBids.setText(
            QtGui.QApplication.translate("MainWindow", "Bids:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemLocation.setText(
            QtGui.QApplication.translate("MainWindow", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemStarts.setText(
            QtGui.QApplication.translate("MainWindow", "Starts:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemEnds.setText(
            QtGui.QApplication.translate("MainWindow", "Ends:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemHighBidder.setText(
            QtGui.QApplication.translate("MainWindow", "High Bidder:", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemBids.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemHighBidder.setText(
            QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemLocation.setText(
            QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemStart.setText(
            QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemEnd.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemLotNumber.setText(
            QtGui.QApplication.translate("MainWindow", "Lot #", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemLotNumber.setText(
            QtGui.QApplication.translate("MainWindow", "000000", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_itemListingNumber.setText(
            QtGui.QApplication.translate("MainWindow", "Listing #", None, QtGui.QApplication.UnicodeUTF8))
        self.val_itemListingNumber.setText(
            QtGui.QApplication.translate("MainWindow", "000000", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_myAccount.setTabText(self.tab_myAccount.indexOf(self.tab),
                                      QtGui.QApplication.translate("MainWindow", "Item", None,
                                                                   QtGui.QApplication.UnicodeUTF8))
        self.tab_myAccount.setTabText(self.tab_myAccount.indexOf(self.tab_browse),
                                      QtGui.QApplication.translate("MainWindow", "Browse", None,
                                                                   QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(
            QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(
            QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(
            QtGui.QApplication.translate("MainWindow", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(
            QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneral_Help.setText(
            QtGui.QApplication.translate("MainWindow", "&General Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(
            QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSummary_Refresh.setText(
            QtGui.QApplication.translate("MainWindow", "Summary Refresh", None, QtGui.QApplication.UnicodeUTF8))


from PySide import QtWebKit
